import 'trip_model.dart';

List<TripModel> sampleTravelProfiles = [
  TripModel(
    id: '1',
    name: 'Priya Singh',
    profileImage: 'assets/travel2.avif',
    description: 'Love exploring beaches and heritage sites',
    budget: 50000,
    startDate: DateTime(2025, 4, 15),
    endDate: DateTime(2025, 4, 25),
    state: 'Goa',
    district: 'North Goa',
    village: 'Calangute',
    personalityType: 'Adventure',
    age: 26,
    gender: 'Female',
    imagePaths: [],
  ),
  TripModel(
    id: '2',
    name: 'Raj Kumar',
    profileImage: 'assets/travel2.avif',
    description: 'Budget traveler, likes local culture',
    budget: 45000,
    startDate: DateTime(2025, 4, 10),
    endDate: DateTime(2025, 4, 28),
    state: 'Goa',
    district: 'South Goa',
    village: 'Palolem',
    personalityType: 'Cultural',
    age: 28,
    gender: 'Male',
    imagePaths: [],
  ),
  TripModel(
    id: '3',
    name: 'Anjali Sharma',
    profileImage: 'assets/travel.avif',
    description: 'Hill station enthusiast',
    budget: 60000,
    startDate: DateTime(2025, 5, 1),
    endDate: DateTime(2025, 5, 10),
    state: 'Himachal Pradesh',
    district: 'Shimla',
    village: 'Kufri',
    personalityType: 'Relaxation',
    age: 24,
    gender: 'Female',
    imagePaths: [],
  ),
  TripModel(
    id: '4',
    name: 'Vikram Patel',
    profileImage: 'assets/travel.avif',
    description: 'Adventure seeker, loves trekking',
    budget: 55000,
    startDate: DateTime(2025, 5, 5),
    endDate: DateTime(2025, 5, 15),
    state: 'Himachal Pradesh',
    district: 'Kullu',
    village: 'Manali',
    personalityType: 'Adventure',
    age: 29,
    gender: 'Male',
    imagePaths: [],
  ),
  TripModel(
    id: '5',
    name: 'Meera Mishra',
    profileImage: 'assets/login.avif',
    description: 'History buff, loves temples',
    budget: 40000,
    startDate: DateTime(2025, 4, 20),
    endDate: DateTime(2025, 5, 5),
    state: 'Tamil Nadu',
    district: 'Chidambaram',
    village: 'Chidambaram',
    personalityType: 'Cultural',
    age: 31,
    gender: 'Female',
    imagePaths: [],
  ),
  TripModel(
    id: '6',
    name: 'Arjun Singh',
    profileImage: 'assets/tel13.avif',
    description: 'Luxury travel lover',
    budget: 100000,
    startDate: DateTime(2025, 4, 1),
    endDate: DateTime(2025, 4, 10),
    state: 'Rajasthan',
    district: 'Jaipur',
    village: 'Central Jaipur',
    personalityType: 'Luxury',
    age: 35,
    gender: 'Male',
    imagePaths: [],
  ),
  TripModel(
    id: '7',
    name: 'Divya Nair',
    profileImage: 'assets/keral7.avif',
    description: 'Backpacker exploring Kerala',
    budget: 35000,
    startDate: DateTime(2025, 5, 15),
    endDate: DateTime(2025, 5, 28),
    state: 'Kerala',
    district: 'Kottayam',
    village: 'Kumarakom',
    personalityType: 'Budget',
    age: 23,
    gender: 'Female',
    imagePaths: [],
  ),
  TripModel(
    id: '8',
    name: 'Rohan Gupta',
    profileImage: 'assets/tel19.avif',
    description: 'Foodie and culture explorer',
    budget: 48000,
    startDate: DateTime(2025, 4, 15),
    endDate: DateTime(2025, 4, 30),
    state: 'Telangana',
    district: 'Hyderabad',
    village: 'Old City',
    personalityType: 'Cultural',
    age: 27,
    gender: 'Male',
    imagePaths: [],
  ),
  TripModel(
    id: '9',
    name: 'Neha Saxena',
    profileImage: 'assets/ty2.avif',
    description: 'Nature lover, forest trekking',
    budget: 52000,
    startDate: DateTime(2025, 4, 20),
    endDate: DateTime(2025, 5, 5),
    state: 'Odisha',
    district: 'Khordha',
    village: 'Bhubaneswar',
    personalityType: 'Adventure',
    age: 25,
    gender: 'Female',
    imagePaths: [],
  ),
  TripModel(
    id: '10',
    name: 'Ashish Kumar',
    profileImage: 'assets/tel21.avif',
    description: 'Beach and water sports fan',
    budget: 60000,
    startDate: DateTime(2025, 4, 10),
    endDate: DateTime(2025, 4, 25),
    state: 'Goa',
    district: 'North Goa',
    village: 'Baga',
    personalityType: 'Adventure',
    age: 26,
    gender: 'Male',
    imagePaths: [],
  ),
];

// Location data for dropdowns
final Map<String, List<String>> stateDistricts = {
  'Goa': ['North Goa', 'South Goa'],
  'Himachal Pradesh': ['Shimla', 'Kullu', 'Manali'],
  'Tamil Nadu': ['Chidambaram', 'Madurai', 'Ooty'],
  'Rajasthan': ['Jaipur', 'Udaipur', 'Jodhpur'],
  'Kerala': ['Kottayam', 'Kochi', 'Thiruvananthapuram'],
  'Telangana': ['Hyderabad', 'Warangal'],
  'Odisha': ['Khordha', 'Balasore'],
};

final Map<String, Map<String, List<String>>> districtVillages = {
  'North Goa': {'Calangute': [], 'Baga': [], 'Anjuna': []},
  'South Goa': {'Palolem': [], 'Benaulim': []},
  'Shimla': {'Kufri': [], 'Chhatnag': []},
  'Kullu': {'Manali': [], 'Bhuntar': []},
  'Chidambaram': {'Chidambaram': []},
  'Jaipur': {'Central Jaipur': [], 'Pink City': []},
  'Kottayam': {'Kumarakom': [], 'Kottayam': []},
  'Hyderabad': {'Old City': [], 'Hitech City': []},
  'Khordha': {'Bhubaneswar': []},
};

final List<String> personalityTypes = [
  'Adventure',
  'Relaxation',
  'Cultural',
  'Luxury',
  'Budget',
];
